insert into products (id, name, category, unit, stock, active, sort_order) values
  ('ail-botte-piece', 'Ail botte', 'Légumes', 'piece', 0, true, 10),
  ('ail-frais-kg', 'Ail frais', 'Légumes', 'kg', 0, true, 11),
  ('ail-sec-kg', 'Ail sec', 'Légumes', 'kg', 0, true, 12),
  ('aubergine-kg', 'Aubergine', 'Légumes', 'kg', 0, true, 13),
  ('basilic-piece', 'Basilic', 'Légumes', 'piece', 0, true, 14),
  ('bette-kg', 'Bette', 'Légumes', 'kg', 0, true, 15),
  ('betterave-crue-kg', 'Betterave crue', 'Légumes', 'kg', 0, true, 16),
  ('carotte-kg', 'Carotte', 'Légumes', 'kg', 0, true, 17),
  ('carotte-botte-kg', 'Carotte botte', 'Légumes', 'kg', 0, true, 18),
  ('celeri-rave-kg', 'Céleri rave', 'Légumes', 'kg', 0, true, 19),
  ('chicoree-pain-de-sucre-kg', 'Chicorée pain de sucre', 'Légumes', 'kg', 0, true, 20),
  ('chicoree-trevise-kg', 'Chicorée trévise', 'Légumes', 'kg', 0, true, 21),
  ('choux-cabus-kg', 'Choux Cabus', 'Légumes', 'kg', 0, true, 22),
  ('choux-chinois-kg', 'Choux chinois', 'Légumes', 'kg', 0, true, 23),
  ('choux-de-printemps-kg', 'Choux de printemps', 'Légumes', 'kg', 0, true, 24),
  ('choux-fleur-kg', 'Choux fleur', 'Légumes', 'kg', 0, true, 25),
  ('choux-frise-kg', 'Choux frisé', 'Légumes', 'kg', 0, true, 26),
  ('choux-rave-kg', 'Choux rave', 'Légumes', 'kg', 0, true, 27),
  ('concombre-kg', 'Concombre', 'Légumes', 'kg', 0, true, 28),
  ('courge-butternut-kg', 'Courge Butternut', 'Légumes', 'kg', 0, true, 29),
  ('courge-carrat-kg', 'Courge Carrat', 'Légumes', 'kg', 0, true, 30),
  ('courge-musquee-kg', 'Courge Musquée', 'Légumes', 'kg', 0, true, 31),
  ('courge-patidou-kg', 'Courge Patidou', 'Légumes', 'kg', 0, true, 32),
  ('courge-potimarron-kg', 'Courge Potimarron', 'Légumes', 'kg', 0, true, 33),
  ('courge-potimarron-vert-kg', 'Courge Potimarron Vert', 'Légumes', 'kg', 0, true, 34),
  ('courgette-pleine-saison-promo-piece', 'Courgette pleine saison promo', 'Légumes', 'piece', 0, true, 35),
  ('courgette-kg', 'Courgette', 'Légumes', 'kg', 0, true, 36),
  ('courgette-serre-kg', 'Courgette serre', 'Légumes', 'kg', 0, true, 37),
  ('echalotte-kg', 'Echalotte', 'Légumes', 'kg', 0, true, 38),
  ('epinard-kg', 'Epinard', 'Légumes', 'kg', 0, true, 39),
  ('fenouil-kg', 'Fenouil', 'Légumes', 'kg', 0, true, 40),
  ('haricot-vert-kg', 'Haricot vert', 'Légumes', 'kg', 0, true, 41),
  ('haricot-serre-kg', 'Haricot serre', 'Légumes', 'kg', 0, true, 42),
  ('laitue-piece', 'Laitue', 'Légumes', 'piece', 0, true, 43),
  ('laitue-serre-piece', 'Laitue serre', 'Légumes', 'piece', 0, true, 44),
  ('laitue-kg', 'laitue', 'Légumes', 'kg', 0, true, 45),
  ('mache-kg', 'Mâche', 'Légumes', 'kg', 0, true, 46),
  ('melon-kg', 'Melon', 'Légumes', 'kg', 0, true, 47),
  ('mesclum-kg', 'Mesclum', 'Légumes', 'kg', 0, true, 48),
  ('navet-kg', 'Navet', 'Légumes', 'kg', 0, true, 49),
  ('navet-botte-piece', 'Navet botte', 'Légumes', 'piece', 0, true, 50),
  ('oignon-kg', 'Oignon', 'Légumes', 'kg', 0, true, 51),
  ('oignon-botte-piece', 'Oignon botte', 'Légumes', 'piece', 0, true, 52),
  ('pasteque-kg', 'Pastèque', 'Légumes', 'kg', 0, true, 53),
  ('panais-kg', 'Panais', 'Légumes', 'kg', 0, true, 54),
  ('patate-douce-kg', 'Patate douce', 'Légumes', 'kg', 0, true, 55),
  ('pdt-primeur-kg', 'PDT primeur', 'Légumes', 'kg', 0, true, 56),
  ('pdt-primeur-saison-kg', 'PDT primeur saison', 'Légumes', 'kg', 0, true, 57),
  ('pdt-conservation-kg', 'PDT conservation', 'Légumes', 'kg', 0, true, 58),
  ('persil-piece', 'Persil', 'Légumes', 'piece', 0, true, 59),
  ('poireaux-kg', 'Poireaux', 'Légumes', 'kg', 0, true, 60),
  ('poivron-kg', 'Poivron', 'Légumes', 'kg', 0, true, 61),
  ('poivron-mini-sucre-kg', 'Poivron mini sucre', 'Légumes', 'kg', 0, true, 62),
  ('radis-botte-piece', 'Radis botte', 'Légumes', 'piece', 0, true, 63),
  ('radis-daikon-kg', 'Radis daïkon', 'Légumes', 'kg', 0, true, 64),
  ('radis-noir-kg', 'Radis noir', 'Légumes', 'kg', 0, true, 65),
  ('tomate-ancienne-kg', 'Tomate ancienne', 'Légumes', 'kg', 0, true, 66),
  ('tomate-cerise-kg', 'Tomate cerise', 'Légumes', 'kg', 0, true, 67),
  ('tomate-ronde-kg', 'Tomate ronde', 'Légumes', 'kg', 0, true, 68),
  ('topinambour-kg', 'Topinambour', 'Légumes', 'kg', 0, true, 69),
  ('confiture-peche-piece', 'Confiture pêche', 'Légumes', 'piece', 0, true, 70),
  ('confiture-peche-gingembre-piece', 'Confiture pêche gingembre', 'Légumes', 'piece', 0, true, 71),
  ('conserve-apero-courgette-piece', 'Conserve apéro courgette', 'Légumes', 'piece', 0, true, 72),
  ('conserve-cardons-piece', 'Conserve cardons', 'Légumes', 'piece', 0, true, 73),
  ('conserve-coulis-tomate-piece', 'Conserve coulis tomate', 'Légumes', 'piece', 0, true, 74),
  ('conserve-ketchup-piece', 'Conserve ketchup', 'Légumes', 'piece', 0, true, 75),
  ('conserve-pesto-basilic-piece', 'Conserve pesto basilic', 'Légumes', 'piece', 0, true, 76),
  ('conserve-pickles-choux-fleur-piece', 'Conserve pickles choux fleur', 'Légumes', 'piece', 0, true, 77),
  ('conserve-pickles-concombre-piece', 'Conserve pickles concombre', 'Légumes', 'piece', 0, true, 78),
  ('chips-piece', 'chips', 'Légumes', 'piece', 0, true, 79),
  ('tartinade-aubergine-piece', 'tartinade aubergine', 'Légumes', 'piece', 0, true, 80),
  ('pickles-ail-piece', 'pickles ail', 'Légumes', 'piece', 0, true, 81),
  ('biere-blonde-ambree-ipa-33cl-piece', 'bière Blonde / Ambrée /Ipa 33cl', 'Légumes', 'piece', 0, true, 82),
  ('biere-blonde-ambree-ipa-75cl-piece', 'bière Blonde / Ambrée /Ipa 75cl', 'Légumes', 'piece', 0, true, 83),
  ('basilic-bouquet-piece', 'basilic bouquet', 'Légumes', 'piece', 0, true, 302),
  ('betterave-kg', 'betterave', 'Légumes', 'kg', 0, true, 303),
  ('blette-kg', 'blette', 'Légumes', 'kg', 0, true, 304),
  ('blette-couleur-botte-piece', 'Blette couleur botte', 'Légumes', 'piece', 0, true, 305),
  ('carotte-botte-piece', 'carotte botte', 'Légumes', 'piece', 0, true, 306),
  ('celeri-branche-kg', 'celeri branche', 'Légumes', 'kg', 0, true, 307),
  ('cebette-piece', 'cebette', 'Légumes', 'piece', 0, true, 309),
  ('chicoree-de-trevise-kg', 'chicorée de trévise', 'Légumes', 'kg', 0, true, 310),
  ('chou-chinois-pak-choi-kg', 'chou chinois/pak choi', 'Légumes', 'kg', 0, true, 312),
  ('chou-kale-piece', 'chou kale', 'Légumes', 'piece', 0, true, 313),
  ('chou-lisse-chou-rouge-pointu-kg', 'chou lisse/chou rouge/pointu', 'Légumes', 'kg', 0, true, 314),
  ('concombre-epineux-kg', 'concombre épineux', 'Légumes', 'kg', 0, true, 315),
  ('concombre-lisse-piece-piece', 'concombre lisse piece', 'Légumes', 'piece', 0, true, 316),
  ('courge-butternut-potimarron-kg', 'courge butternut/potimarron', 'Légumes', 'kg', 0, true, 317),
  ('courge-muscade-bleue-kg', 'courge muscade/bleue', 'Légumes', 'kg', 0, true, 318),
  ('courge-spaghetti-kg', 'courge spaghetti', 'Légumes', 'kg', 0, true, 320),
  ('courgette-debut-et-fin-de-saison-kg', 'courgette debut et fin de saison', 'Légumes', 'kg', 0, true, 321),
  ('courgette-juillet-aout-kg', 'courgette juillet aout', 'Légumes', 'kg', 0, true, 322),
  ('courgette-jaune-blanche-ronde-kg', 'courgette jaune, blanche ,ronde', 'Légumes', 'kg', 0, true, 323),
  ('fenouil-piece', 'fenouil', 'Légumes', 'piece', 0, true, 326),
  ('haricot-vert-plat-kg', 'haricot vert/ plat', 'Légumes', 'kg', 0, true, 328),
  ('mache-mesclum-kg', 'mache/mesclum', 'Légumes', 'kg', 0, true, 330),
  ('navet-violet-jaune-kg', 'navet violet/jaune', 'Légumes', 'kg', 0, true, 331),
  ('navet-daikon-kg', 'navet daikon', 'Légumes', 'kg', 0, true, 332),
  ('oignon-rouge-blanc-kg', 'oignon rouge/blanc', 'Légumes', 'kg', 0, true, 334),
  ('patate-douce-gros-calibre-kg', 'patate douce gros calibre', 'Légumes', 'kg', 0, true, 337),
  ('persil-frise-bouquet-piece', 'persil frisé bouquet', 'Légumes', 'piece', 0, true, 338),
  ('persil-plat-bouquet-piece', 'persil plat bouquet', 'Légumes', 'piece', 0, true, 339),
  ('poireau-kg', 'poireau', 'Légumes', 'kg', 0, true, 340),
  ('poivron-vert-kg', 'poivron vert', 'Légumes', 'kg', 0, true, 341),
  ('poivron-couleur-kg', 'poivron couleur', 'Légumes', 'kg', 0, true, 342),
  ('pdt-consommation-maiwen-blanche-kg', 'pdt consommation Maiwen blanche', 'Légumes', 'kg', 0, true, 343),
  ('pdt-nouvelle-rouge-kg', 'pdt nouvelle rouge', 'Légumes', 'kg', 0, true, 344),
  ('pdt-nouvelle-jaune-kg', 'pdt nouvelle jaune', 'Légumes', 'kg', 0, true, 345),
  ('pdt-sac-2-5-kg', 'pdt sac 2,5', 'Légumes', 'kg', 0, true, 346),
  ('potimarron-orange-vert-kg', 'potimarron orange/ vert', 'Légumes', 'kg', 0, true, 347),
  ('radis-noir-violet-redd-meat-kg', 'radis noir, violet, redd meat…', 'Légumes', 'kg', 0, true, 349),
  ('rutabaga-panais-kg', 'rutabaga/panais', 'Légumes', 'kg', 0, true, 350),
  ('tomate-ancienne-rouge-kg', 'tomate ancienne rouge', 'Légumes', 'kg', 0, true, 351),
  ('tomate-ancienne-jaune-piece', 'tomate ancienne jaune', 'Légumes', 'piece', 0, true, 352),
  ('tomate-ancienne-rose-piece', 'tomate ancienne rose', 'Légumes', 'piece', 0, true, 353),
  ('ipa', 'Bière IPA', 'Bières', 'unite', 96, true, 900),
  ('blonde-carton', 'Bière blonde - carton 12', 'Bières', 'carton', 20, true, 910)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  unit = excluded.unit,
  stock = excluded.stock,
  active = excluded.active,
  sort_order = excluded.sort_order;

insert into product_prices (price_list_id, product_id, price) values
  ('tarif-epicerie', 'ail-botte-piece', 2.2),
  ('tarif-epicerie', 'ail-frais-kg', 8.8),
  ('tarif-epicerie', 'ail-sec-kg', 7.34),
  ('tarif-epicerie', 'aubergine-kg', 3.86),
  ('tarif-epicerie', 'basilic-piece', 1.2),
  ('tarif-epicerie', 'bette-kg', 2.95),
  ('tarif-epicerie', 'betterave-crue-kg', 2.5),
  ('tarif-epicerie', 'carotte-kg', 2.65),
  ('tarif-epicerie', 'carotte-botte-kg', 2.67),
  ('tarif-epicerie', 'celeri-rave-kg', 2.9645),
  ('tarif-epicerie', 'chicoree-pain-de-sucre-kg', 3.6784),
  ('tarif-epicerie', 'chicoree-trevise-kg', 3.6784),
  ('tarif-epicerie', 'choux-cabus-kg', 2.5047),
  ('tarif-epicerie', 'choux-chinois-kg', 3.6784),
  ('tarif-epicerie', 'choux-de-printemps-kg', 2.8556),
  ('tarif-epicerie', 'choux-fleur-kg', 3.3033),
  ('tarif-epicerie', 'choux-frise-kg', 2.5047),
  ('tarif-epicerie', 'choux-rave-kg', 2.7588),
  ('tarif-epicerie', 'concombre-kg', 3.3033),
  ('tarif-epicerie', 'courge-butternut-kg', 2.51),
  ('tarif-epicerie', 'courge-carrat-kg', 2.51),
  ('tarif-epicerie', 'courge-musquee-kg', 2.36),
  ('tarif-epicerie', 'courge-patidou-kg', 2.51),
  ('tarif-epicerie', 'courge-potimarron-kg', 2.51),
  ('tarif-epicerie', 'courge-potimarron-vert-kg', 2.51),
  ('tarif-epicerie', 'courgette-pleine-saison-promo-piece', 2.32),
  ('tarif-epicerie', 'courgette-kg', 2.6375),
  ('tarif-epicerie', 'courgette-serre-kg', 3.6925),
  ('tarif-epicerie', 'echalotte-kg', 6),
  ('tarif-epicerie', 'epinard-kg', 4.2),
  ('tarif-epicerie', 'fenouil-kg', 3.48),
  ('tarif-epicerie', 'haricot-vert-kg', 6.9),
  ('tarif-epicerie', 'haricot-serre-kg', 8),
  ('tarif-epicerie', 'laitue-piece', 1.05),
  ('tarif-epicerie', 'laitue-serre-piece', 1.2),
  ('tarif-epicerie', 'laitue-kg', 3.5),
  ('tarif-epicerie', 'mache-kg', 13.1136),
  ('tarif-epicerie', 'melon-kg', 2.6343),
  ('tarif-epicerie', 'mesclum-kg', 13.1136),
  ('tarif-epicerie', 'navet-kg', 2.5652),
  ('tarif-epicerie', 'navet-botte-piece', 2.1121),
  ('tarif-epicerie', 'oignon-kg', 2.86),
  ('tarif-epicerie', 'oignon-botte-piece', 2.205),
  ('tarif-epicerie', 'pasteque-kg', 2.09),
  ('tarif-epicerie', 'panais-kg', 3.03),
  ('tarif-epicerie', 'patate-douce-kg', 4.0462),
  ('tarif-epicerie', 'pdt-primeur-kg', 5.05),
  ('tarif-epicerie', 'pdt-primeur-saison-kg', 3.22),
  ('tarif-epicerie', 'pdt-conservation-kg', 1.76),
  ('tarif-epicerie', 'persil-piece', 1.2),
  ('tarif-epicerie', 'poireaux-kg', 3.025),
  ('tarif-epicerie', 'poivron-kg', 3.9204),
  ('tarif-epicerie', 'poivron-mini-sucre-kg', 7.3447),
  ('tarif-epicerie', 'radis-botte-piece', 1.6),
  ('tarif-epicerie', 'radis-daikon-kg', 2.9403),
  ('tarif-epicerie', 'radis-noir-kg', 2.9403),
  ('tarif-epicerie', 'tomate-ancienne-kg', 3.95),
  ('tarif-epicerie', 'tomate-cerise-kg', 6.3),
  ('tarif-epicerie', 'tomate-ronde-kg', 2.9),
  ('tarif-epicerie', 'topinambour-kg', 4.009),
  ('tarif-epicerie', 'confiture-peche-piece', 3.6),
  ('tarif-epicerie', 'confiture-peche-gingembre-piece', 3.23),
  ('tarif-epicerie', 'conserve-apero-courgette-piece', 2.9),
  ('tarif-epicerie', 'conserve-cardons-piece', 4.8),
  ('tarif-epicerie', 'conserve-coulis-tomate-piece', 2.42),
  ('tarif-epicerie', 'conserve-ketchup-piece', 3.23),
  ('tarif-epicerie', 'conserve-pesto-basilic-piece', 4.03),
  ('tarif-epicerie', 'conserve-pickles-choux-fleur-piece', 3.23),
  ('tarif-epicerie', 'conserve-pickles-concombre-piece', 3.63),
  ('tarif-epicerie', 'chips-piece', 2.28),
  ('tarif-epicerie', 'tartinade-aubergine-piece', 3.63),
  ('tarif-epicerie', 'pickles-ail-piece', 3.63),
  ('tarif-epicerie', 'biere-blonde-ambree-ipa-33cl-piece', 1.8),
  ('tarif-epicerie', 'biere-blonde-ambree-ipa-75cl-piece', 3.7),
  ('tarif-mercuriale-2026', 'ail-frais-kg', 8.6),
  ('tarif-mercuriale-2026', 'aubergine-kg', 3.1),
  ('tarif-mercuriale-2026', 'basilic-bouquet-piece', 1.1),
  ('tarif-mercuriale-2026', 'betterave-kg', 2.26),
  ('tarif-mercuriale-2026', 'blette-kg', 3.1),
  ('tarif-mercuriale-2026', 'blette-couleur-botte-piece', 1.8),
  ('tarif-mercuriale-2026', 'carotte-botte-piece', 2.14),
  ('tarif-mercuriale-2026', 'celeri-branche-kg', 3.1),
  ('tarif-mercuriale-2026', 'celeri-rave-kg', 2.8),
  ('tarif-mercuriale-2026', 'cebette-piece', 2.06),
  ('tarif-mercuriale-2026', 'chicoree-de-trevise-kg', 3.35),
  ('tarif-mercuriale-2026', 'chicoree-pain-de-sucre-kg', 2.95),
  ('tarif-mercuriale-2026', 'chou-chinois-pak-choi-kg', 3.3),
  ('tarif-mercuriale-2026', 'chou-kale-piece', 1.5),
  ('tarif-mercuriale-2026', 'chou-lisse-chou-rouge-pointu-kg', 2.2),
  ('tarif-mercuriale-2026', 'concombre-epineux-kg', 3.2),
  ('tarif-mercuriale-2026', 'concombre-lisse-piece-piece', 1.3),
  ('tarif-mercuriale-2026', 'courge-butternut-potimarron-kg', 2.2),
  ('tarif-mercuriale-2026', 'courge-muscade-bleue-kg', 2.1),
  ('tarif-mercuriale-2026', 'courge-patidou-kg', 2.9),
  ('tarif-mercuriale-2026', 'courge-spaghetti-kg', 2),
  ('tarif-mercuriale-2026', 'courgette-debut-et-fin-de-saison-kg', 2.65),
  ('tarif-mercuriale-2026', 'courgette-juillet-aout-kg', 2.15),
  ('tarif-mercuriale-2026', 'courgette-jaune-blanche-ronde-kg', 2.15),
  ('tarif-mercuriale-2026', 'echalotte-kg', 5.3),
  ('tarif-mercuriale-2026', 'epinard-kg', 4.35),
  ('tarif-mercuriale-2026', 'fenouil-piece', 3.35),
  ('tarif-mercuriale-2026', 'haricot-serre-kg', 8),
  ('tarif-mercuriale-2026', 'haricot-vert-plat-kg', 6.9),
  ('tarif-mercuriale-2026', 'laitue-piece', 1.1),
  ('tarif-mercuriale-2026', 'mache-mesclum-kg', 12),
  ('tarif-mercuriale-2026', 'navet-violet-jaune-kg', 2.26),
  ('tarif-mercuriale-2026', 'navet-daikon-kg', 2.6),
  ('tarif-mercuriale-2026', 'oignon-botte-piece', 2.06),
  ('tarif-mercuriale-2026', 'oignon-rouge-blanc-kg', 3),
  ('tarif-mercuriale-2026', 'pasteque-kg', 2),
  ('tarif-mercuriale-2026', 'patate-douce-kg', 3.3),
  ('tarif-mercuriale-2026', 'patate-douce-gros-calibre-kg', 2.8),
  ('tarif-mercuriale-2026', 'persil-frise-bouquet-piece', 1.1),
  ('tarif-mercuriale-2026', 'persil-plat-bouquet-piece', 1.1),
  ('tarif-mercuriale-2026', 'poireau-kg', 2.98),
  ('tarif-mercuriale-2026', 'poivron-vert-kg', 3.1),
  ('tarif-mercuriale-2026', 'poivron-couleur-kg', 3.75),
  ('tarif-mercuriale-2026', 'pdt-consommation-maiwen-blanche-kg', 1.7),
  ('tarif-mercuriale-2026', 'pdt-nouvelle-rouge-kg', 4.5),
  ('tarif-mercuriale-2026', 'pdt-nouvelle-jaune-kg', 4.5),
  ('tarif-mercuriale-2026', 'pdt-sac-2-5-kg', 4.6),
  ('tarif-mercuriale-2026', 'potimarron-orange-vert-kg', 2.2),
  ('tarif-mercuriale-2026', 'radis-botte-piece', 1.6),
  ('tarif-mercuriale-2026', 'radis-noir-violet-redd-meat-kg', 2.6),
  ('tarif-mercuriale-2026', 'rutabaga-panais-kg', 2.75),
  ('tarif-mercuriale-2026', 'tomate-ancienne-rouge-kg', 3.95),
  ('tarif-mercuriale-2026', 'tomate-ancienne-jaune-piece', 3.95),
  ('tarif-mercuriale-2026', 'tomate-ancienne-rose-piece', 3.95),
  ('tarif-mercuriale-2026', 'tomate-ronde-kg', 2.9),
  ('tarif-mercuriale-2026', 'tomate-cerise-kg', 5.3),
  ('tarif-epicerie', 'ipa', 3.2),
  ('tarif-mercuriale-2026', 'ipa', 3.2),
  ('tarif-epicerie', 'blonde-carton', 34),
  ('tarif-mercuriale-2026', 'blonde-carton', 34)
on conflict (price_list_id, product_id) do update set
  price = excluded.price;
